apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: dbpedia
  name: dbpedia-tls
  namespace: dbpedia
spec:
  dnsNames:
  - dbpedia.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  secretName: dbpedia-tls
  usages:
  - digital signature
  - key encipherment